### ISSUE TITLE
Refinery does not pause production at 100%

### ISSUE THREAD

**Issue by c1ph3r88** [Dubwise56/Rimefeller#3]
The refinery will not pause production of fuel if you have the upper limit of the range set to 100%  Dropping it to anything lower than 100% will act as intended, pausing the refinery until it hits your lower limit.

I'm assuming maybe a rounding issue with percentages?

https://imgur.com/DZvuyyx

**Comment by Dubwise56** [comment]
this doesn't appear to happen now so probably got fixed
