### ISSUE TITLE
Colored Synthelline Components Missing in 1.1?

### ISSUE THREAD

**Issue by rschmukler** [Dubwise56/Rimefeller#8]
Hey! It looks like all of the colored syntheline variants are commented out in 1.1 currently. Is this intentional?

**Comment by Dubwise56** [comment]
yes i removed them because my paint shop does a better job of it

**Comment by rschmukler** [comment]
Oh! Awesome, I didn't even know that existed. I'll just install that then. Thanks for all your work modding!
